### ISSUE TITLE
Feature for clustering station on the map

### ISSUE THREAD

**Issue by tadeze** [SensorDX/issue_tracker#2]
It might not be a big issue but I found this leaflet (leaflet.markercluster) https://github.com/Leaflet/Leaflet.markercluster, an add-in that supports clustering similar maps. It looks good on the map. I wonder if it is not hard to include on the map it will look great.

**Comment by renay007** [comment]
Great minds do think alike! This is exactly the next feature I was going to include after getting finals out of the way :-)
Expect to see this feature in the next major update 💯  🥇 👍

**Comment by tadeze** [comment]
Grea!! Good luck with your finals!!
