### ISSUE TITLE
Link to Ticket Included on Automated Email to Technician 

### ISSUE THREAD

**Issue by thuyvyng** [SensorDX/issue_tracker#22]
When a ticket is issued or when the network manager is commenting, a link to the ticket should be included in the automated email to the technician.

**Comment by thuyvyng** [comment]
It should just be "https://tahmoissuetracker.mybluemix.net/#/issues/view/:id" so i just need to create string of the base url and concat it with the issue.id and add it to sendmail functions

**Comment by RickHagenaars** [comment]
Yes it would simply be that link which is the most important thing.
It would however also be very nice to have the link work when you were not logged in yet (cache the URL and redirect after login).

**Comment by thuyvyng** [comment]
![Screen Shot 2021-01-16 at 3 23 11 PM](https://user-images.githubusercontent.com/43559792/104827062-cacab200-580e-11eb-86e4-542d80ed8e04.png)
Screenshot of email that I sent to myself. I made it so that you can click on the blue text but I can change the formatting of the email if desired

**Comment by thuyvyng** [comment]
<img width="1098" alt="Screen Shot 2021-04-06 at 1 15 47 PM" src="https://user-images.githubusercontent.com/43559792/113772943-34ee4700-96da-11eb-8c1b-7d69c31afd6b.png">
