### ISSUE TITLE
Enable Subscriptions/Assignments for Automated Emails

### ISSUE THREAD

**Issue by thuyvyng** [SensorDX/issue_tracker#23]
Enable me (the network manager) to assign a ticket to more than one person or at least to assign to one person and subscribe some more so that they too receive automated email.

**Comment by thuyvyng** [comment]
for this one, would it be to format it similarly to the label problems where its more of a checkbox and you can select multiple users?

**Comment by thuyvyng** [comment]
<img width="1288" alt="Screen Shot 2020-12-12 at 9 50 11 PM" src="https://user-images.githubusercontent.com/43559792/102004267-05977280-3cc4-11eb-8613-8dc898009e2c.png">
Here is an example of how it would look!

**Comment by RickHagenaars** [comment]
Discussed with Bokure: His preferred option would be to assign to a single person and have the option to subscribe one or more others. I think that would also make it simpler for you since nothing would change in the database.

**Comment by thuyvyng** [comment]
For the formatting of subscribers would having another dropdown checkbox menu thats labeled as subscribers be sufficient? So that it would be how it looks currently but next to label it has "Subscribers" which a drop down checkbox menu? Let me know if youd like me to code it up and give a screenshot.

**Comment by RickHagenaars** [comment]
> For the formatting of subscribers would having another dropdown checkbox menu thats labeled as subscribers be sufficient? So that it would be how it looks currently but next to label it has "Subscribers" which a drop down checkbox menu? Let me know if youd like me to code it up and give a screenshot.

Yes the example screenshot you made with the multi-select would be perfect, we'll just use the multi-select for "subscribers" and keep the "assigned" to a single person.

**Comment by thuyvyng** [comment]
Do you also want the functionality to view and/ or edit subscribers once they have been established? (I noticied that you aren't able to view the labels when simply just viewing an issue but that you were able to edit it afterwards)

**Comment by thuyvyng** [comment]
<img width="1215" alt="Screen Shot 2021-02-10 at 6 26 13 PM" src="https://user-images.githubusercontent.com/43559792/107596734-7b895e80-6bcd-11eb-9320-27201dc44c27.png">
as an update this is how it should look

**Comment by thuyvyng** [comment]
I think I accomplished this. However, I am unsure of how to test it.

**Comment by thuyvyng** [comment]
<img width="1440" alt="Screen Shot 2021-04-03 at 1 11 57 PM" src="https://user-images.githubusercontent.com/43559792/113490353-2c99d000-947e-11eb-8013-270cc57f24a8.png">
