### ISSUE TITLE
Sorting/Filtering of tickets

### ISSUE THREAD

**Issue by thuyvyng** [SensorDX/issue_tracker#25]
I need to rearrange the tickets according to station id, opening date, closing date, ticket number etc.

**Comment by thuyvyng** [comment]
I remembered I asked but I wanted to be a little more concrete with written instruction. Would this be like a filtering option where a user can only show things with specific station id? Similar to how it currently has a country filter, assignee filter? Or would this be actually rearranging and allowing the user to determine if they want the lowest or highest value first. For example, in shopping you can decide to shop from low to high or high to low and theres a sort of drop down menu for users to decide how they want to view the issues?

**Comment by RickHagenaars** [comment]
Discussed with Bokure: He wants ordering, not filtering. Exactly what you discribed in the TS.

**Comment by thuyvyng** [comment]
I did some examples just to see if this is what is wanted. Here i created buttons above where the issues are. Here in my screenshots you can see that when I click on the updated button it orders it by either most recent or least recently updated. 
<img width="1362" alt="Screen Shot 2021-01-21 at 12 37 50 PM" src="https://user-images.githubusercontent.com/43559792/105409714-b8bd8a80-5be5-11eb-8ba3-3b562169fa15.png">
<img width="1362" alt="Screen Shot 2021-01-21 at 12 37 46 PM" src="https://user-images.githubusercontent.com/43559792/105409726-bbb87b00-5be5-11eb-97cd-d3b6362a4055.png"> Does this look good? (I can edit the styling and actual appearance of these buttons later on, I just want to make sure this is wanted before I put the time in for that). And I just wanted to check on what other buttons are wanted for now I know of: station id, updated, opening_date, ticket number

**Comment by RickHagenaars** [comment]
Yes this is exactly what Bokure wanted.
Opening date and ticket number will be the exact same order, so please only put "Ticket number" in.

**Comment by thuyvyng** [comment]
Question: Do you want these filter tags on all of the tickets (open, pending, closed, all) or just on some of them?

**Comment by thuyvyng** [comment]
<img width="1440" alt="Screen Shot 2021-02-07 at 3 42 17 PM" src="https://user-images.githubusercontent.com/43559792/107162908-19292780-695b-11eb-8ddc-ce15f9c82e0f.png">

**Comment by RickHagenaars** [comment]
> Question: Do you want these filter tags on all of the tickets (open, pending, closed, all) or just on some of them?

Yes that would be great.

**Comment by thuyvyng** [comment]
Should be done

**Comment by thuyvyng** [comment]
<img width="1440" alt="Screen Shot 2021-04-03 at 1 13 37 PM" src="https://user-images.githubusercontent.com/43559792/113490394-68349a00-947e-11eb-80d3-454c7d6c2fcb.png">
Fixed the error that Bokure mentioned in email. I was ordering them by alphabetical order instead of numerical, it should be fixed now let me know if there are still errors.
