### ISSUE TITLE
Fix to Only Edit Own Comments

### ISSUE THREAD

**Issue by thuyvyng** [SensorDX/issue_tracker#26]
It is good to edit a comment but when someone is editing, he or she must able to edit only his or her comment but not others comments especially not the comment of the network manager.

**Comment by thuyvyng** [comment]
Should be done but need to check and test ( ask about how to correct test)

**Comment by thuyvyng** [comment]
Checked, I was able to edit my comments but I was not given the option on anyone elses comments

**Comment by RickHagenaars** [comment]
We also referenced this in #28, but a non-manager should indeed only be able to edit their own comments.
For a manager it would be nice to be able to edit also other comments, but that's not really important (only nice to have).

**Comment by thuyvyng** [comment]
Sounds good, I have now updated it so that a user can either edit a comment if it is their comment OR if they are a manager
