### ISSUE TITLE
Close & Open Tickets for Network Manager Only

### ISSUE THREAD

**Issue by thuyvyng** [SensorDX/issue_tracker#28]
Button such us “Close” and “open tickets” better to be accessible to the network manager only

**Comment by thuyvyng** [comment]
<img width="1402" alt="Screen Shot 2020-12-09 at 11 53 00 AM" src="https://user-images.githubusercontent.com/43559792/101680122-179fb980-3a15-11eb-9ef1-179065482508.png">

**Comment by thuyvyng** [comment]
here i have a check to see if the user has type role == manager, if they do not the button just doesnt show up and heres a screenshot of what it looks like originally to compare
<img width="1402" alt="Screen Shot 2020-12-09 at 11 55 08 AM" src="https://user-images.githubusercontent.com/43559792/101680331-63eaf980-3a15-11eb-8fb7-f80d3cb50c44.png">

**Comment by RickHagenaars** [comment]
Discussed with Bokure:
An account which does not have the "manager" role can only create a comment or edit their own comment.
All the buttons on the ticket level (edit/new issue/close issue/pending) should be usable only for the manager. Also editing comments from other users should only be possible for the manager.

Please note this will also include the "New issue" button in the search bar.

**Comment by thuyvyng** [comment]
![Screen Shot 2021-01-16 at 2 28 10 PM](https://user-images.githubusercontent.com/43559792/104824541-74a64080-5807-11eb-9116-c3392a37cc88.png)
![Screen Shot 2021-01-16 at 2 27 47 PM](https://user-images.githubusercontent.com/43559792/104824542-77089a80-5807-11eb-828b-8e006e4652b4.png)
![Screen Shot 2021-01-16 at 2 24 46 PM](https://user-images.githubusercontent.com/43559792/104824543-77a13100-5807-11eb-811e-ac2eeb1b1238.png)
I believe that I have accomplished everything you mentioned above. Let me know if any of the sceenshots look wrong
