### ISSUE TITLE
Creation Date -> Latest Comment Timestamp

### ISSUE THREAD

**Issue by thuyvyng** [SensorDX/issue_tracker#29]
On the search view, the dates on the right should indicate the last update on the ticket. I mean it should show the time of the latest comment put on it. It is often showing the creation time. [Need to test.]

**Comment by thuyvyng** [comment]
<img width="1393" alt="Screen Shot 2020-11-30 at 6 48 36 PM" src="https://user-images.githubusercontent.com/43559792/100691031-a9843400-333c-11eb-8d53-55eb91434d6d.png">
I think this is correct, it is update time not creation time

**Comment by thuyvyng** [comment]
![Screen Shot 2020-12-02 at 3 49 25 PM](https://user-images.githubusercontent.com/43559792/100945616-6c43b180-34b6-11eb-9e36-bfa8540b74f1.png)

Option 1 is changing it to be how long it's been since updated

**Comment by thuyvyng** [comment]
![Screen Shot 2020-12-02 at 3 54 25 PM](https://user-images.githubusercontent.com/43559792/100945723-aa40d580-34b6-11eb-9ced-7b4b9af1794a.png)

**Comment by RickHagenaars** [comment]
Discussed with Bokure, he would like option 1 where you have the time interval since the last update/last comment.

I think the reason you might be having the creation time there often is that a comment might not actually update the timestamp on a ticket itself.

**Comment by thuyvyng** [comment]
![Screen Shot 2021-01-16 at 2 08 52 PM](https://user-images.githubusercontent.com/43559792/104824152-60147900-5804-11eb-807a-580c9e9941db.png)
Here's the screenshot confirming that it has now been updated. Just wanted to check if there were other changes on this such as changing the calendar icon or what you wanted to do with the "updated ...." on the right side of the issue (seen in first screenshot on this issue).
