### ISSUE TITLE
Color Adjustments

### ISSUE THREAD

**Issue by thuyvyng** [SensorDX/issue_tracker#30]
The highlights of the label need adjustment, like for sensor failure with red, battery issues with yellow, communication problem blue, and general maintenance grey.

**Comment by thuyvyng** [comment]
![Uploading Screen Shot 2020-11-16 at 9.55.09 AM.png…]()

**Comment by thuyvyng** [comment]
<img width="1346" alt="Screen Shot 2020-11-16 at 9 56 34 AM" src="https://user-images.githubusercontent.com/43559792/99289587-04247880-27f2-11eb-8eea-394f72e2bb8b.png">

**Comment by RickHagenaars** [comment]
Discussed this with Bokure, the new colors in your screenshot are correct.

**Comment by thuyvyng** [comment]
<img width="1440" alt="Screen Shot 2021-04-03 at 12 07 08 PM" src="https://user-images.githubusercontent.com/43559792/113488798-1e938180-9475-11eb-876d-51e03cc72c1c.png">

**Comment by thuyvyng** [comment]
the red colour for the sensor failure is a bit dark so it would be fine if it is a bit light red. this is not big issue though. if you exchange the red for battery issue and the yellow for sensor failure is also very much appreciated.  should be fixed now
