### ISSUE TITLE
Android Mobile Friendly

### ISSUE THREAD

**Issue by thuyvyng** [SensorDX/issue_tracker#32]
Comment can’t be sent from android mobile. when using an android mobile phone you can open the system and write your comments but you can’t send them because the send button is invisible. see screenshot below.

**Comment by thuyvyng** [comment]
<img width="725" alt="Screen Shot 2021-01-21 at 1 27 48 PM" src="https://user-images.githubusercontent.com/43559792/105414534-764b7c00-5bec-11eb-913e-9ede5584fca5.png">


I tried changing my screen dimensions so that it looks like an android but it looks like it the comment button is accessible to me, what are the dimensions of the phones that have issues?

**Comment by RickHagenaars** [comment]
I asked Bokure whether he can replicate the issue on his android phone but it seems to be working fine for him.
We'll contact Victor which reported the issue and let you know the specifics.

**Comment by thuyvyng** [comment]
According to Feb 10th meeting, this issue is okay to be closed
