### ISSUE TITLE
remove all credentials from the source code

### ISSUE THREAD

**Issue by thuyvyng** [SensorDX/issue_tracker#33]

**Comment by thuyvyng** [comment]
does this just mean completely removing the links to the databases in connections and requiring user to have it set locally on their process.env

**Comment by RickHagenaars** [comment]
A user doesn't run the issue tracker on it's local machine but rather uses the cloud deployed version. Just for the cloud deployment in general those process environment variables would be configured in the VCAP (like how it's already being used for the mail settings).

**Comment by thuyvyng** [comment]
as a progress update,  i have removed credentials and stored them as process.env as DB_1 & DB_2 respectively --- works!
