### ISSUE TITLE
[MEDIUM] Display station information

### ISSUE THREAD

**Issue by RickHagenaars** [SensorDX/issue_tracker#7]
Page: /#/issues

On the issue overview page the station identifier is currently prepended to the issue title.
We would like to expand this further with the datalogger identifier and site name.

Please use the structure %STATION_ID%/%DATALOGGER_ID%, %SITE_NAME% - %ISSUE_TITLE%.
E.g.: "TA00356/06-00905, Loima Boys High School - sim card not active"

Page: /#/issues/view/5b68573f495675000eec8037
On the issue view page this information should also be prepended to the title, please use the same structure as described above.

**Comment by renay007** [comment]
Please inform all managers and field agents that they no longer need to put the Station Information in the  ISSUE_TITLE.

If they continue to do so, they will see duplicate station information.
E.g.: "TA00356/06-00905, Loima Boys High School - TA00356/06-00905, Loima Boys High School "
